import React from "react";
import Resume from "./components/resumeJobs"

const prevJobs = [
    {
        id: 11,
        title: "Front Desk Receptionist",
        company: "Overlake Medical Center, Clincs & Hospital",
        contract: false,
        contractCompany: null,
        dateFinish: "September 2022",
        dateStart: "June 2022",
        description: "Working the main lobby at Overlake Medical Center my responsibilities were to ensure that all guests and staff that entered the building were wearing proper PPE. Also screening people and asking the hospital provided questionnaire to ensure a safe environment for everyone. After screening I would help patients and visitors get to the department they were looking for. While making sure to confirm with staff at different parts of the hospital that patients could have guests as there are restrictions due to COVID-19 & Monkey Pox.",
    },
    {
        id: 10,
        title: "Math Tutor",
        company: "Singapore Maths Club",
        contract: true,
        contractCompany: "Singapore Maths Club",
        dateFinish: "June 2022",
        dateStart: "January 2022",
        description: "This position has me teaching 5th grade students basic algebra and other advanced level math strategies for their age group. This is a work from home job that has me teaching remotely through zoom for hour and 15 min class sessions for multiple classes a week. Making sure that I stay within my budgeted time while also getting through the material is paramount in this position. The usual class size ranges from 6 to 14 kids and making part of the challenge is ensuring that they are all paying attention as well as being involved with the classwork. Other duties include working with other staff to make sure that the material is being presented just as the curriculum was intended to be taught.",
    },
    {
        id: 9,
        title: "Patient Service Representative",
        company: "First Hill Surgery Center",
        contract: true,
        contractCompany: "NuWest Group",
        dateFinish: "June 2020",
        dateStart: "January 2022",
        description: "This is a customer service position first and foremost. All starting with checking the patient in for their surgery, this includes their insurance as well as other forms of identification and collecting any payments that are due at the time of service. Making sure that the patients have a ride home. Other responsibilities include collecting required consent forms from other departments from within the building as well as contacting outside clinics for additional information. Answering the phone and being able to answer basic questions about the clinic as well as forwarding calls to different departments when the information is outside of my expertise.",
    },
    {
        id: 8,
        title: "Patient Care Coordinator",
        company: "Seattle Cancer Care Association",
        contract: true,
        contractCompany: "NuWest Group",
        dateFinish: "January 2022",
        dateStart: "October 2021",
        description: "This position has me filling in for the different Team Coordinators throughout our Bone Marrow Transplant Clinic as well as working the front desk on occasion. My role has me working with different providers and departments throughout the SCCA building as well as South Lake Union and the University of Washington. Making appointments for patients, as well as working with our staff to ensure that their schedule is clean and balanced. The job requires heavy amounts of multitasking as a coordinator is responsible for multiple teams that take care of multiple patients each. Being able to get a task finished quickly and efficiently is paramount as patients need different diagnostic appointments done before procedure. With limited availability for those appointments it's my job to be able to rapidly reconfigure a patient's schedule to make it happen",
    },
    {
        id: 7,
        title: "Administative Assistant",
        company: "Seattle Cancer Care Association",
        contract: true,
        contractCompany: "NuWest Group",
        dateFinish: "October 2021",
        dateStart: "August 2021",
        description: "Working the vaccine clinics' front desk my position's responsibilities were to print and prepare paperwork for patients to fill out. Check in patients for their appointments or to add walk-in's into our system. Using EPIC to handle patient information for various tasks related to their appointment. As well as inputting their vaccination information to the state immunization records and SCCA's record deposits. The position had me working with a wide array of office software and hardware including Teams, Outlook and Word. Working with the nurses, pharmacists and other administration we make sure to process patients quickly, safely and without error.",
    },
    {
        id: 6,
        title: "Front Desk Receptionist",
        company: "Overlake Medical Center, Clincs & Hospital",
        contract: true,
        contractCompany: "NuWest Group",
        dateFinish: "July 2021",
        dateStart: "March 2021",
        description: "Working the main lobby at Overlake Medical Center my responsibilities were to ensure that all guests and staff that entered the building were wearing proper PPE. Also screening people and asking the hospital provided questionnaire to ensure a safe environment for everyone. After screening I would help patients and visitors get to the department they were looking for. While making sure to confirm with staff at different parts of the hospital that patients could have guests as there were restrictions due to COVID-19.",
    },
    {
        id: 5,
        title: "Deli Manager",
        company: "Kroger (QFC)",
        contract: false,
        contractCompany: null,
        dateFinish: "March 2021",
        dateStart: "June 2020",
        description: "My job had me making orders, organizing the upkeep in the department as well as making sure that customers receive the service they are looking for. I made the schedules for our employees making sure to work with them so they get the time slots they are looking for and I am within our labor budgeting. Communication was key in this position and making sure that everyone is up to speed on everything going on is paramount. Sending emails to upper management to ensure that tasks are getting done, we receive the supplies that we need and any incidents are reported.",
    },
    {
        id: 4,
        title: "Kitchen Lead",
        company: "New Seasons Market",
        contract: false,
        contractCompany: null,
        dateFinish: "June 2020",
        dateStart: "October 2018",
        description: "Customer service and leadership were the two things that were key in this position. Leading a crew to make sure that the kitchen was both properly supplied for the next day and that customers were happy and dealt with in a timely manner. I was in charge of the daily schedule including lunch breaks and each person's role for the shift. I was also first contact for any customer that had a question or issue with our service. Making sure to inform management of how the night went with emails and verbal communication every shift.",
    },
    {
        id: 3,
        title: "Night Shift Manager",
        company: "Grocery Outlet",
        contract: false,
        contractCompany: null,
        dateFinish: "May 2018",
        dateStart: "November 2018",
        description: "My responsibilities are to run the registers and help provide customers with the best experience I can provide by helping them find items when they can not and to help keep the line moving quickly and effectively through my check out line while also, bagging each item for the customer and stocking the grocery items needed on the floor while customer volume is low. During my time as a manager I help create schedules and ensure that breaks were taken during shift. I did some ordering for portions of the store and assisted with loading orders.",
    },
    {
        id: 2,
        title: "Saucer Batch Operator",
        company: "Kerry Foods & Ingredients",
        contract: false,
        contractCompany: null,
        dateFinish: "March 2018",
        dateStart: "April 2017",
        description: "This position required me to prepare a batch mixture for production to be sent out to customers. My responsibilities were to get the machine prepped for cooking and transfer as well as making sure that it was cleaned out at the end of the production schedule. At times having to operate a forklift to retrieve ingredients and rearrange pallets. When batching I had to catalog times that events occur during the creation of a batch, including when main ingredients are added and at what temperature goals are hit. Ingredients used, how much was used and their corresponding lot numbers to ensure that the correct materials were being used. At the end of the production schedule I was in charge of setting up the batching system for cleaning until Sanitation crew arrived. Depending on the product I had to enter our chemical cage and set the system up for soaking before doing a full CIP process.",
    },
    {
        id: 1,
        title: "Line Operator",
        company: "Hormel Foods",
        contract: false,
        contractCompany: null,
        dateFinish: "March 2017",
        dateStart: "March 2012",
        description: "Working as the main operator of food production for pillow packed products my responsibilities were to ensure the line ran consistently. This included supervising the staff the operated the lower functions of the machine as well as maintaining the hardware during production. During my time as the operator we broke production records as well as safety, while also eliminating 90% of accidental waste incidents.",
    },
]

function App(){
    return <Resume prevJobs={prevJobs} />;
}

export default App;